# Generated by Django 6.0.6 on 2026-06-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('initial', models.CharField(max_length=5)),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('stipend', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('is_trending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
