# Generated by Django 6.0.6 on 2026-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=20)),
                ('gradient', models.CharField(max_length=100)),
            ],
        ),
    ]
