# Generated by Django 6.0.6 on 2026-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_question_testattempt_studentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('marks', models.IntegerField(default=50)),
                ('statement', models.TextField()),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('sample_input', models.TextField(blank=True)),
                ('sample_output', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='coding_questions/')),
                ('starter_code', models.TextField(default='def solve():\n    pass\n\nif __name__ == "__main__":\n    solve()\n')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
