# Generated by Django 6.0.6 on 2026-07-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_codingquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Expected output for the official input'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='official_input',
            field=models.TextField(blank=True, help_text='Input used during submission evaluation'),
        ),
    ]
