# Generated by Django 6.0.6 on 2026-07-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_codingquestion_expected_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('grammar', 'Grammar MCQ'), ('listening', 'Listening'), ('grammar_situation', 'Grammar Situation'), ('email', 'Email Writing'), ('expression', 'Thought Expression')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('marks', models.IntegerField(default=2)),
                ('option1', models.CharField(blank=True, max_length=255)),
                ('option2', models.CharField(blank=True, max_length=255)),
                ('option3', models.CharField(blank=True, max_length=255)),
                ('option4', models.CharField(blank=True, max_length=255)),
                ('correct_option', models.CharField(blank=True, help_text='A/B/C/D', max_length=1)),
                ('audio', models.FileField(blank=True, null=True, upload_to='communication_audio/')),
                ('expected_answer', models.TextField(blank=True)),
                ('sample_answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
