# Generated by Django 6.0.6 on 2026-07-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_communicationquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationquestion',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='communicationquestion',
            old_name='option1',
            new_name='option_a',
        ),
        migrations.RenameField(
            model_name='communicationquestion',
            old_name='option2',
            new_name='option_b',
        ),
        migrations.RenameField(
            model_name='communicationquestion',
            old_name='option3',
            new_name='option_c',
        ),
        migrations.RenameField(
            model_name='communicationquestion',
            old_name='option4',
            new_name='option_d',
        ),
    ]
