# Generated by Django 6.0.6 on 2026-07-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_communicationquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
    ]
