# Generated by Django 6.0.6 on 2026-08-01 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_communicationanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('self_intro', 'Self Introduction'), ('strength_weakness', 'Strengths & Weaknesses'), ('career_goal', 'Career Goals'), ('leadership', 'Leadership'), ('teamwork', 'Teamwork'), ('problem_solving', 'Problem Solving'), ('behavioral', 'Behavioral Questions'), ('company_fit', 'Company Fit')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('marks', models.IntegerField(default=10)),
                ('sample_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HRAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('marks_obtained', models.IntegerField(default=0)),
                ('evaluated', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hrquestion')),
            ],
        ),
    ]
